import { Inter } from "next/font/google";
import { connection } from "next/server";
import "./globals.css";
import "./jash.css";
import "./shivam.css"
import LayoutShell from "@/components/LayoutShell";

const inter = Inter({
  variable: "--font-inter",
  subsets: ["latin"],
});

export const metadata = {
  title: "Microsite",
  description: "Generated by create next app",
};

export default async function RootLayout({ children }) {
  await connection();
  return (
    <html lang="en">
      <body className={`${inter.variable} ${inter.className}`}>
        <LayoutShell>{children}</LayoutShell>
      </body>
    </html>
  );
}
